### ISSUE TITLE
Create a new user/account for each device (currently is hard-coded)

### ISSUE THREAD

**Issue by jbrain98** [cs394-w20/fab#105]

**Comment by szaslan** [comment]
Working on this

**Comment by szaslan** [comment]
Use this ID https://docs.expo.io/versions/latest/sdk/constants/#constantsinstallationid

**Comment by jdanene** [comment]
Technally implemented. db.createRoom.js the function that starts at line35 does this

**Comment by sujunglee** [comment]
@jdanene Yep, I think we still need to make it so that the app automatically create a new account BEFORE the person creates a room

**Comment by jbrain98** [comment]
yea sorry i did all of this, in a pull request
