### ISSUE TITLE
my post page - for each post display either the checkmark icon if complete or "time left..."

### ISSUE THREAD

**Issue by jbrain98** [cs394-w20/fab#159]
https://drive.google.com/drive/u/1/folders/15nlpQrtwDhfVZjsqqVAyjYlNe7KEEk0e
match ui given

**Comment by sujunglee** [comment]
<img width="457" alt="Screen Shot 2020-03-09 at 8 58 18 PM" src="https://user-images.githubusercontent.com/24560111/76272208-be69e600-6248-11ea-88e4-d8de98c37644.png">
